### ISSUE TITLE
2d keypoint is available?

### ISSUE THREAD

**Issue by ilikeokoge** [skelemoa/quovadis#1]
Thanks for publishing usuful datasets.
In Skeleton-Kinetics, 2d keypoint information (+ confidence) per frame is available.
In Your dataset, only 3d keypoint information (xyz by VIBE) is available?
Or 2d keypoint information(+ confidence) of openpose able to be calculated by the 3d information?

**Comment by Anirudh257** [comment]
@ilikeokoge Thanks for your interest in our work. In Skeletics-Kinetics, only 3D skeleton are available. Confidence has not been used by us in our datasets.

**Comment by ilikeokoge** [comment]
I see. Thanks for your comments!
