### ISSUE TITLE
Graph Structure of  Shift-GCN for Skeletics-152

### ISSUE THREAD

**Issue by fmthoker** [skelemoa/quovadis#2]
Hi, I was wondering whether the graph structure for skeletics-152 is the same as that of  NTU RGB+D.  In other words,  do we need to change this graph (https://github.com/kchengiva/Shift-GCN/tree/master/graph) while using skeletics-152 ?

**Comment by Anirudh257** [comment]
@fmthoker skeletics-152 is following the graph structure of VIBE(openpose). You can check the structure here: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#keypoint-ordering-in-cpython
