### ISSUE TITLE
Can't download Skeletics 152 dataset

### ISSUE THREAD

**Issue by ericwang0701** [skelemoa/quovadis#3]
Thank you for sharing your amazing work and dataset. I have tried to download the Skeletics 152 dataset, but I always got failed-network errors during the process. I have double-checked my disk space and used different browsers, but it still always failed.

Is there any chance that you can host the file somewhere else? Any suggestions on how to download it successfully would be really helpful.

Besides, I'd like to know if the dataset also includes the original video link so that I can render the results along with the video.

Thank you so much for o your time and help.

**Comment by Anirudh257** [comment]
@ericwang0701 Apologies for the inconvenience caused. We are looking up the cause of the issue.

**Comment by ericwang0701** [comment]
Any update on this? If possible, it would be very helpful if you can share each video link that you reconstructed the 3D pose for the Skeletics 152 dataset. Thanks.

**Comment by Anirudh257** [comment]
@ericwang0701 We are working on this issue. I will share the link for the dataset as soon as possible.

**Comment by Anirudh257** [comment]
@ericwang0701 We have uploaded the Skeletics-152 dataset here: https://zenodo.org/record/4515787. Apologies for the time taken.

**Comment by asetsuna** [comment]
Hi, appreciate for your great work. We find the download link of zenodo does't support resume from break. As the whole file is really large,  we tried serveral times to download it and failed. Can you please give a hand for solving this problem ?
