### ISSUE TITLE
How to use VIBE to generate skeleton data for Metaphorics dataset

### ISSUE THREAD

**Issue by ericwang0701** [skelemoa/quovadis#4]
Thank you for sharing your amazing work and dataset. I'd like to know how you used VIBE to generate the skeleton data for Metaphorics dataset. VIBE results will become unreliable if there is no visible full-body as shown below.
![Alt Text](https://media.giphy.com/media/huFmeMyyVjpCYRo4GZ/giphy.gif)

Any suggestions on how you addressed this issue and generate good skeleton data even when only half-body is visible would be really appreciated. Thanks

**Comment by Anirudh257** [comment]
@ericwang0701 Thanks for your interest in our work and this good question. In our work on Metaphorics, we restrict ourselves to **noun-based charades** actions and curate videos giving proper VIBE output [partial/complete human pose]. You can see more details here: https://skeleton.iiit.ac.in/datasets.
