### ISSUE TITLE
Cannot download the Skeletics 152 Dataset

### ISSUE THREAD

**Issue by canbaoburen** [skelemoa/quovadis#6]
Hi,

   I am unable to download the Skeletics 15 dataset since it would interrupt after I download only about 10 Gb. So I wonder if there is an alternative link that I can try to download the dataset.  

Best

**Comment by MKA-12** [comment]
@canbaoburen Thank you for showing interest in our work! 
We have checked the link to the Skeletics-152 dataset on Zenodo ( https://zenodo.org/record/4515787 ) and it is working fine. 

Unfortunately, there is no alternative link available as of now. Kindly check the network connection on your side and retry.
