### ISSUE TITLE
Can I know the frame size where joints are extracted from? I want to get relative size and position of bounding boxes .

### ISSUE THREAD

**Issue by Haetsal-Lee** [skelemoa/quovadis#8]
Can I know the frame size where joints are extracted from? I want to get relative size and position of bounding boxes .

**Comment by Anirudh257** [comment]
@Haetsal-Lee what do you mean by the frame size exactly? We use VIBE to get the respective data from a curated set of classes.

**Comment by Haetsal-Lee** [comment]
> @Haetsal-Lee what do you mean by the frame size exactly? We use VIBE to get the respective data from a curated set of classes.

I mean the frame size of video. I want to know width and height of each frame.

In json files of Skeletics dataset you shared, there is a "bboxes" field. And there are stored as absolute coordinate. (Not by relative coordinates). And I want to get relative coordinate of bboxes. This is why I want to know the frame sizes you used.

**Comment by Anirudh257** [comment]
@Haetsal-Lee, the frame size for the videos is variable.

**Comment by Haetsal-Lee** [comment]
> @Haetsal-Lee, the frame size for the videos is variable.

Yes yes I know that sizes are variable.
And also when you download a video from Yotube, depending an option you choose sizes become different.

**Comment by Anirudh257** [comment]
@Haetsal-Lee We didn't specify the video size parameters and just downloaded the video uploaded to Youtube in its original dimensions.
