### ISSUE TITLE
About the index of joints of Skeletics 152 

### ISSUE THREAD

**Issue by canbaoburen** [skelemoa/quovadis#9]
Hi, 
     In the Scripts/parse_vibe_data.py,  the reqd_joints are set as [38, 43, 44, 45, 46, 47, 48, 40, 37, 33,32,31, 34,35,36, 41, 39, 27,26,25, 28,29,30, 22, 19].  What are these joints? Are they are still the joints of openpose?

Best.

**Comment by neel1998** [comment]
Sorry for the late response.

VIBE gives SMPL style 3d joint information for the estimated pose, but for our experiments we use only the joints corresponding/similar to NTU Kinect skeleton representation. This https://github.com/mkocabas/VIBE/blob/c0c3f77d587351c806e901221a9dc05d1ffade4b/lib/data_utils/kp_utils.py#L212 provides the order of joints that are given by VIBE, from this we select the joints corresponding to the NTU kinect skeleton.

I hope this clarifies your doubt.

**Comment by canbaoburen** [comment]
@neel1998 Thanks for your kind reply! So there are some differences between the codes and the discriptions of '_VIBE pose estimate gives 49 joints in total out of which we are choosing the first 25 body joints common with Openpose. The joint ordering for Openpose is here. '_ ? I am asking the problem since I am using the dataset. Hope to your reply soon.

**Comment by pranaygupta36** [comment]
Hi @canbaoburen, you are right, the joints mentioned in the script are not from openpose. From the 49 joints listed in [https://github.com/mkocabas/VIBE/blob/c0c3f77d587351c806e901221a9dc05d1ffade4b/lib/data_utils/kp_utils.py#L212 ](this function), the first 25 are openpose joints, we take 23(removed the jaw) out of the remaining 24, and take big toe and small toe from openpose to obtain the 25 joints in skeletics.

Thanks for pointing it out, we will correct the description.
